const ACTION_TYPES = {
    SET_IS_LOADING: 'SET_IS_LOADING',
    FETCH_OBJECTS_BY_PARAMS: 'FETCH_OBJECTS_BY_PARAMS',
    FETCH_OBJECTS_ALL: 'FETCH_OBJECTS_ALL',

    // Object
    SET_OBJECT: 'SET_OBJECT',
    CLEAR_OBJECT: 'CLEAR_OBJECT',

    // Events
    SET_OBJECT_EVENTS: 'SET_OBJECT_EVENTS',
    CLEAR_OBJECT_EVENTS: 'CLEAR_OBJECT_EVENTS',

    // User
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_USER_PROFILE: 'FETCH_USER_PROFILE'
};

export default ACTION_TYPES;