export const TYPES = {
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_LIST_OBJECTS: 'SET_LIST_OBJECTS',
  SET_OBJECTS: 'SET_OBJECTS',

  // Object
  SET_OBJECT: 'SET_OBJECT',
  CLEAR_OBJECT: 'CLEAR_OBJECT',

  // Events
  SET_OBJECT_EVENTS: 'SET_OBJECT_EVENTS',
  CLEAR_OBJECT_EVENTS: 'CLEAR_OBJECT_EVENTS'
}
